// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYL-BsbL1SnN27lxV1Gbwq3tjB-S8-r-Q',
    appId: '1:1017699560420:web:fbab203b644b69d0b7f5f1',
    messagingSenderId: '1017699560420',
    projectId: 'clone-1613f',
    authDomain: 'clone-1613f.firebaseapp.com',
    storageBucket: 'clone-1613f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_DPtxHeIMejK8Do_sDKLRudZpus3h1KM',
    appId: '1:1017699560420:android:b3a0410aa62cc24fb7f5f1',
    messagingSenderId: '1017699560420',
    projectId: 'clone-1613f',
    storageBucket: 'clone-1613f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-M4BGjNd2MsUfZhgmBw8pUoeDL8wWe40',
    appId: '1:1017699560420:ios:8812e6201bd099c2b7f5f1',
    messagingSenderId: '1017699560420',
    projectId: 'clone-1613f',
    storageBucket: 'clone-1613f.appspot.com',
    iosBundleId: 'com.example.paypalClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-M4BGjNd2MsUfZhgmBw8pUoeDL8wWe40',
    appId: '1:1017699560420:ios:614a70a6dfd999f3b7f5f1',
    messagingSenderId: '1017699560420',
    projectId: 'clone-1613f',
    storageBucket: 'clone-1613f.appspot.com',
    iosBundleId: 'com.example.paypalClone.RunnerTests',
  );
}
